#!/bin/bash

DIRECTORY="/mnt/games/SteamLibrary"
CFG_PATH="$DIRECTORY/steamapps/common/Counter-Strike\ Global\ Offensive/game/csgo/cfg"
CFG_PATH_ESCAPED="${CFG_PATH//\\ / }"                                              

for file in *.cfg; do 
	if [ -L "$CFG_PATH_ESCAPED/$file" ]; then
		echo -e "\e[33mSkipped: $file (already linked)\e[0m"
	elif [ -e "$CFG_PATH_ESCAPED/$file" ]; then
		echo -e "\e[33mSkipped: $file (file already exists)\e[0m"
	elif ln -s "./$file" "$CFG_PATH_ESCAPED/$file" 2>/dev/null; then
		echo -e "\e[32mLinked: $file -> $CFG_PATH_ESCAPED/$file\e[0m"
	else
		echo -e "\e[31mFailed to link: $file\e[0m"
	fi
done

echo "Linked cs2 config files. Found in $CFG_PATH"
